from core import run_infer_script



params = {'input_path': 'assets/audios/tomas_vowels.wav', 
          'output_path': 'assets/audios/tomas_vowels_output.wav', 
          'pth_path': 'logs/maria-20/maria-20.pth', 
          'index_path': '', 
          'pitch': 0, 
          'index_rate': 0.75, 
          'volume_envelope': 1, 
          'protect': 0.5, 
          'hop_length': 128, 
          'f0_method': 'rmvpe', 
          #'pth_path': 'logs/maria-20/maria-20.pth', 
          'split_audio': False, 
          'f0_autotune': False, 
          'f0_autotune_strength': 1, 
          'clean_audio': False, 
          'clean_strength': 0.5, 
          'export_format': 'WAV', 
          'f0_file': None, 
          'embedder_model': 'contentvec', 
          'embedder_model_custom': None, 
          'post_process': False, 
          'formant_shifting': False, 
          'formant_qfrency': 1, 
          'formant_timbre': 1, 
          'reverb': False, 
          'pitch_shift': False, 
          'limiter': False, 
          'gain': False, 
          'distortion': False, 
          'chorus': False, 
          'bitcrush': False, 
          'clipping': False, 
          'compressor': False, 
          'delay': False, 
          'reverb_room_size': 0.5, 
          'reverb_damping': 0.5, 
          'reverb_wet_gain': 0.33, 
          'reverb_dry_gain': 0.4, 
          'reverb_width': 1, 
          'reverb_freeze_mode': 0, 
          'pitch_shift_semitones': 0, 
          'limiter_threshold': -6, 
          'limiter_release_time': 0.05, 
          'gain_db': 0, 
          'distortion_gain': 25, 
          'chorus_rate': 1, 
          'chorus_depth': 0.25, 
          'chorus_center_delay': 7, 
          'chorus_feedback': 0, 
          'chorus_mix': 0.5, 
          'bitcrush_bit_depth': 8, 
          'clipping_threshold': -6, 
          'compressor_threshold': 0, 
          'compressor_ratio': 1, 
          'compressor_attack': 1, 
          'compressor_release': 100, 
          'delay_seconds': 0.5, 
          'delay_feedback': 0, 
          'delay_mix': 0.5, 
          'sid': 0}


# kwargs = {
#         "audio_input_paths": input_folder,
#         "audio_output_path": output_folder,
#         "model_path": pth_path,
#         "index_path": index_path,
#         "pitch": pitch,
#         "index_rate": index_rate,
#         "volume_envelope": volume_envelope,
#         "protect": protect,
#         "hop_length": hop_length,
#         "f0_method": f0_method,
#         "pth_path": pth_path,
#         "index_path": index_path,
#         "split_audio": split_audio,
#         "f0_autotune": f0_autotune,
#         "f0_autotune_strength": f0_autotune_strength,
#         "clean_audio": clean_audio,
#         "clean_strength": clean_strength,
#         "export_format": export_format,
#         "f0_file": f0_file,
#         "embedder_model": embedder_model,
#         "embedder_model_custom": embedder_model_custom,
#         "post_process": post_process,
#         "formant_shifting": formant_shifting,
#         "formant_qfrency": formant_qfrency,
#         "formant_timbre": formant_timbre,
#         "reverb": reverb,
#         "pitch_shift": pitch_shift,
#         "limiter": limiter,
#         "gain": gain,
#         "distortion": distortion,
#         "chorus": chorus,
#         "bitcrush": bitcrush,
#         "clipping": clipping,
#         "compressor": compressor,
#         "delay": delay,
#         "reverb_room_size": reverb_room_size,
#         "reverb_damping": reverb_damping,
#         "reverb_wet_level": reverb_wet_gain,
#         "reverb_dry_level": reverb_dry_gain,
#         "reverb_width": reverb_width,
#         "reverb_freeze_mode": reverb_freeze_mode,
#         "pitch_shift_semitones": pitch_shift_semitones,
#         "limiter_threshold": limiter_threshold,
#         "limiter_release": limiter_release_time,
#         "gain_db": gain_db,
#         "distortion_gain": distortion_gain,
#         "chorus_rate": chorus_rate,
#         "chorus_depth": chorus_depth,
#         "chorus_delay": chorus_center_delay,
#         "chorus_feedback": chorus_feedback,
#         "chorus_mix": chorus_mix,
#         "bitcrush_bit_depth": bitcrush_bit_depth,
#         "clipping_threshold": clipping_threshold,
#         "compressor_threshold": compressor_threshold,
#         "compressor_ratio": compressor_ratio,
#         "compressor_attack": compressor_attack,
#         "compressor_release": compressor_release,
#         "delay_seconds": delay_seconds,
#         "delay_feedback": delay_feedback,
#         "delay_mix": delay_mix,
#         "sid": sid,
#     }


run_infer_script(**params)